---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx.harikumar.dev
  namespace: default
spec:
  secretName: ssl-harikumar-dev
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.harikumar.dev'
  dnsNames:
    - '*.harikumar.dev'